language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
branches:
  only:
    - master

jobs:
  include:
    - stage: "Lint"
      name: "Ng Lint"
      script: npm run lint
    - stage: "Test"
      name: "Unit Tests"
      script: npm run test
      name: "Integration Tests"
    - stage: "Build"
      before_script: npm install -g @angular/cli
      name: "Building app"
      script: ng build --prod --base-href https://bamanczak.github.io/pesel/
    - stage: "Deploy"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/pesel
        on:
          branch: master
